import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        "pag-bg-primary",
        "pag-bg-secondary",
        "pag-bg-tertiary",
        "pag-bg-success",
        "pag-bg-success-light",
        "pag-bg-error",
        "pag-bg-error-light",
        "pag-bg-accent",
        "pag-bg-tag-flex",
        "pag-bg-tag-short",
        "pag-bg-tag-playercount",
        "pag-bg-tag-downvotecount",
        "pag-bg-tag-long",
        "pag-bg-tag-interested",
        "pag-bg-tag-not-interested",

        "pag-border-primary",
        "pag-border-secondary",
        "pag-border-success",
        "pag-border-success-light",
        "pag-border-error",
        "pag-border-error-light",
        "pag-border-tag",
        "pag-border-tag-not-interested",
        "pag-border-tag-short",
        "pag-border-tag-playercount",
        "pag-border-tag-downvotecount",
        "pag-border-tag-long",
        "pag-border-tag-flex",
        "pag-border-tag-interested",

        "pag-scrollbar-track",
        "pag-scrollbar-thumb",

        "pag-text-primary",
        "pag-text-muted",
        "pag-text-success",
        "pag-text-error",
        "pag-text-tag-short",
        "pag-text-tag-playercount",
        "pag-text-tag-downvotecount",
        "pag-text-tag-long",
        "pag-text-tag-flex",
        "pag-text-tag-interested",
        "pag-text-tag-not-interested",

        "pag-icon-primary",
        "pag-icon-primary-hover",
        "pag-icon-success",
        "pag-icon-success-hover",
        "pag-icon-error",
        "pag-icon-tag-interested",
        "pag-icon-error-disabled",
        "pag-icon-stat",
        "pag-icon-award",
      ],
      radius: ["pag-sm", "pag-main", "pag-full"],
      spacing: [
        "pag-spacing-1",
        "pag-spacing-25",
        "pag-spacing-50",
        "pag-spacing-75",
        "pag-spacing-100",
        "pag-spacing-125",
        "pag-spacing-150",
        "pag-spacing-200",
        "pag-spacing-300",
        "pag-spacing-400",
        "pag-spacing-500",
        "pag-spacing-600",
        "pag-spacing-800",

        "pag-sizing-1",
        "pag-sizing-25",
        "pag-sizing-50",
        "pag-sizing-75",
        "pag-sizing-100",
        "pag-sizing-150",
        "pag-sizing-200",
        "pag-sizing-300",
        "pag-sizing-400",
        "pag-sizing-500",
        "pag-sizing-600",
        "pag-sizing-800",
      ],
      font: ["pag-default"],
      ],
      text: ["pag-xs", "pag-sm", "pag-md", "pag-lg", "pag-xl", "pag-2xl"],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
